name: AlpineLinux
on: [push]
jobs:
  build-on-alpine:
    container: alpine:3.13.2

    steps:
      - uses: actions/checkout@v2
      
      - run: pwd && ls
      - run: apk add libc-dev gcc make automake autoconf pkgconf git file diffutils

      - run: cc --version

      - run: git clone https://github.com/universal-ctags/ctags
      - run: cd ctags
      - run: ./autogen.sh
      - run: ./configure --prefix=/usr
      - run: make
      - run: sudo make install
      - run: file /usr/bin/ctags
      - run: ctags --version
      - run: make check
