name: ci workflow

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:
    # https://docs.github.com/en/free-pro-team@latest/actions/reference/specifications-for-github-hosted-runners#supported-runners-and-hardware-resources
    strategy:
      matrix:
        os: [ubuntu-16.04, ubuntu-18.04, ubuntu-20.04, macos-11.0, macos-10.15]

    runs-on: ${{ matrix.os }}
    
    steps:
    - name: export -p
      run:  export -p

    - name: python --version
      run: |
        command -v python
        python --version
        python -V

    - name: list all bins
      run: |
        for path in $(echo "$PATH" | tr : ' ')
        do
            for item in $(ls "$path" 2> /dev/null)
            do
                COMMAND="$path/$item"
                if [ -f "$COMMAND" -a -x "$COMMAND" ] ; then
                    printf "|%15s|%s|\n" "$item" "$COMMAND"
                fi
            done
        done
