name: cross compile with mingw-w64
on: [push]
jobs:
  compile:
    strategy:
      fail-fast: false
      matrix:
        build-machine-os: [ubuntu-16.04, ubuntu-18.04, ubuntu-20.04, macos-10.15]
        target-arch: [i686,x86_64]
    env:
      TARGET:  ${{ matrix.target-arch }}-w64-mingw32
      CC:      ${{ matrix.target-arch }}-w64-mingw32-gcc
      AR:      ${{ matrix.target-arch }}-w64-mingw32-ar
      RANLIB:  ${{ matrix.target-arch }}-w64-mingw32-ranlib
      WINDRES: ${{ matrix.target-arch }}-w64-mingw32-windres
      CFLAGS:  -v

    runs-on: ${{ matrix.build-machine-os }}

    steps:
      #- uses: actions/checkout@v2
      
      - run: brew install mingw-w64 gcc make automake autoconf file

      - run: git clone https://github.com/universal-ctags/ctags
      - run: mv ctags/* .
      - run: ./autogen.sh
      - run: ./configure --host=$TARGET --disable-iconv --disable-xml --disable-json --disable-yaml CC=$CC CFLAGS=$CFLAGS AR=$AR RANLIB=$RANLIB WINDRES=$WINDRES
      - run: make V=1
      - run: file ctags.exe | grep PE32
