name: Cygwin
on: [push]
jobs:
  build-on-Cygwin:
    runs-on: windows-latest

    steps:
    - run: pwd
    - uses: actions/checkout@v2
    - run: pwd

    - run: Invoke-WebRequest -OutFile setup-x86_64.exe "http://cygwin.com/setup-x86_64.exe"

    - run: .\setup-x86_64.exe -qnNd -P git,gcc-g++,make,automake,autoconf,pkg-config,dos2unix,libiconv-devel,libjansson-devel,libxml2-devel,libyaml-devel

    - run: |
        run() {
            printf "\033[0;35m==>\033[0m \033[0;32m%b\n\033[0m" "$*"
            $@
        }
        run pwd
        run env
        run git clone https://github.com/universal-ctags/ctags
        run cd ctags
        
        run ./autogen.sh
        run ./configure --prefix=/usr
        run make V=1
        run file ./ctags.exe
        run ./ctags.exe --version
        run make check V=1 APPVEYOR=1
        run make roundtrip
      shell: bash
