name: Cygwin
on: [push]
jobs:
  build-on-Cygwin:
    runs-on: windows-latest

    steps:
    - uses: actions/checkout@v2

    - run: choco install -y --source cygwin gcc-g++ make automake autoconf pkg-config dos2unix libiconv-devel libjansson-devel libxml2-devel libyaml-devel

    - run: |
        run() {
            printf "\033[0;35m==>\033[0m \033[0;32m%b\n\033[0m" "$*"
            $@
        }
        run pwd
        run env
        run ls /bin
        run git clone https://github.com/universal-ctags/ctags
        run cd ctags
        
        run ./autogen.sh
        run ./configure --prefix=/usr
        run make V=1
        run file ./ctags.exe
        run ./ctags.exe --version
        run make check V=1 APPVEYOR=1
        run make roundtrip
      shell: C:\tools\cygwin\bin\bash.exe -lie {0}
