name: Cygwin
on: [push]
jobs:
  build-on-Cygwin:
    runs-on: windows-latest

    env:
      BASH: C:\tools\cygwin\bin\bash.exe -l -i -e -c

    steps:
      #- uses: actions/checkout@v2

    - run: choco install -y --source cygwin gcc-g++ make automake autoconf pkg-config dos2unix libiconv-devel libjansson-devel libxml2-devel libyaml-devel

    - run: $BASH git clone https://github.com/universal-ctags/ctags
    - run: $BASH mv ctags/* .
    - run: $BASH ./autogen.sh
    - run: $BASH ./configure --prefix=/usr
    - run: $BASH make V=1
    - run: $BASH file ./ctags.exe
    - run: $BASH ./ctags.exe --version
    - run: $BASH make check V=1 APPVEYOR=1
    - run: $BASH make roundtrip
