name: msys2
on: [push]
jobs:
  build-on-msys2:
    runs-on: windows-latest

    defaults:
      run:
        shell: msys2 {0}

    steps:
    - uses: actions/checkout@v2

    - uses: msys2/setup-msys2@v2
      with:
        msystem: MINGW64
        update: true
        install: git gcc make automake autoconf pkg-config unix2dos

    - run: pwd
    - run: ls
    
    - run: git clone https://github.com/universal-ctags/ctags
    - run: cd ctags

    - run: cc --version

    - run: ./autogen.sh
    - run: ./configure --prefix=/usr
    - run: make
    - run: make install
    - run: file /usr/bin/ctags
    - run: ctags --version
    - run: make check
    - run: make roundtrip
