name: msys2
on: [push]
jobs:
  build-on-msys2:
    runs-on: windows-latest

    strategy:
      fail-fast: false
      matrix:
        msystem: [MSYS, MINGW32, MINGW64]

    defaults:
      run:
        shell: msys2 {0}

    steps:
    - uses: actions/checkout@v2

    - uses: msys2/setup-msys2@v2
      with:
        msystem: ${{ matrix.msystem }}
        update: true
        install: git make automake1.16 autoconf pkg-config dos2unix

    - if:  matrix.msystem == 'MSYS'
      run: pacman -S --noconfirm gcc libiconv-devel

    - if:  matrix.msystem == 'MINGW32'
      run: pacman -S --noconfirm mingw-w64-i686-toolchain

    - if:  matrix.msystem == 'MINGW64'
      run: pacman -S --noconfirm mingw-w64-x86_64-toolchain

    - run: ln -s /usr/bin/automake-1.16 /usr/bin/automake
    - run: ln -s /usr/bin/aclocal-1.16  /usr/bin/aclocal

    - run: git clone https://github.com/universal-ctags/ctags
    
    - run: |
        run() {
            printf "\033[0;35m==>\033[0m \033[0;32m%b\n\033[0m" "$*"
            $@
        }
        
        run cd ctags
        
        run ./autogen.sh
        run ./configure --prefix=/usr
        run make V=1
        run make install
        run file /usr/bin/ctags
        run ctags --version
        run make check
        run make roundtrip
