name: MSYS2
on: [push]
jobs:
  build-on-MSYS2:
    runs-on: windows-latest

    strategy:
      fail-fast: false
      matrix:
        msystem: [MSYS, MINGW32, MINGW64]

    defaults:
      run:
        shell: msys2 {0}

    steps:
    - uses: actions/checkout@v2

    - uses: msys2/setup-msys2@v2
      with:
        msystem: ${{ matrix.msystem }}
        update: true
        install: git make automake autoconf pkg-config python dos2unix

    - if:  matrix.msystem == 'MSYS'
      run: pacman -S --noconfirm gcc libiconv-devel

    - if:  matrix.msystem == 'MINGW32'
      run: pacman -S --noconfirm mingw-w64-i686-toolchain

    - if:  matrix.msystem == 'MINGW64'
      run: pacman -S --noconfirm mingw-w64-x86_64-toolchain

    - run: |
        run() {
            printf "\033[0;35m==>\033[0m \033[0;32m%b\n\033[0m" "$*"
            $@
        }
        run cd /c/Windows/System32 
        run git clone https://github.com/universal-ctags/ctags
        run cd ctags
        
        run ./autogen.sh
        run ./configure --prefix=/usr
        run make V=1
        run file ./ctags.exe
        run ./ctags.exe --version
        run make check V=1
        run make roundtrip
