name: NetBSD
on: [push]
jobs:
  build-on-openbsd:
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@v2

      - uses: leleliu008/github-actions-vagrant@v1
        with:
          mem: 2048
          box: generic/netbsd9
          run: |
            run() {
              printf "\033[0;35m==>\033[0m \033[0;32m%b\n\033[0m" "$*"
              $@
            }

            run sudo pkgin -y install mozilla-rootcerts git automake pkg-config

            run sudo mozilla-rootcerts install

            run cc --version

            run git clone https://github.com/universal-ctags/ctags
            run cd ctags
            run ./autogen.sh
            run ./configure --prefix=/usr
            run make
            run file /usr/bin/ctags
            run ctags --version
