name: run units target on NetBSD

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  testing:
    runs-on: macos-10.15
    
    steps:
    - uses: actions/checkout@v2
    
    - run: vagrant init generic/netbsd9
    - run: cp NetBSD/Vagrantfile .
    - run: vagrant up --provision
